class NewsPaperRunner1
{
  public static void main(String[] news)
  {
     
	 NewsPaper1 ref = new NewsPaper1();
	 ref.currentAffairs();
	 ref.companyName = "Insight Outlet";
	 ref.noOfPages = "8";
	 ref.language = "English";
	 ref.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref.companyName);
  System.out.println("The noOfPages is "+ ref.noOfPages);
  System.out.println("The language is "+ ref.language);
  System.out.println("The price is "+ ref.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref1 = new NewsPaper1();
	 ref1.currentAffairs();
	 ref1.companyName = "Patriot Journal";
	 ref1.noOfPages = "5";
	 ref1.language = "Kannada";
	 ref1.price = 30;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref1.companyName);
  System.out.println("The noOfPages is "+ ref1.noOfPages);
  System.out.println("The language is "+ ref1.language);
  System.out.println("The price is "+ ref1.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref2 = new NewsPaper1();
	 ref2.currentAffairs();
	 ref2.companyName = "Amar Ujala";
	 ref2.noOfPages = "8";
	 ref2.language = "Hindi";
	 ref2.price = 10;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref2.companyName);
  System.out.println("The noOfPages is "+ ref2.noOfPages);
  System.out.println("The language is "+ ref2.language);
  System.out.println("The price is "+ ref2.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref3 = new NewsPaper1();
	 ref3.currentAffairs();
	 ref3.companyName = "Times Insight";
	 ref3.noOfPages = "8";
	 ref3.language = "Hindi";
	 ref3.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref3.companyName);
  System.out.println("The noOfPages is "+ ref3.noOfPages);
  System.out.println("The language is "+ ref3.language);
  System.out.println("The price is "+ ref3.price);
  System.out.println("-------------------------------------------------------------------");
   NewsPaper1 ref4 = new NewsPaper1();
	 ref4.currentAffairs();
	 ref4.companyName = "Greater kashmir";
	 ref4.noOfPages = "9";
	 ref4.language = "English";
	 ref4.price = 30;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref4.companyName);
  System.out.println("The noOfPages is "+ ref4.noOfPages);
  System.out.println("The language is "+ ref4.language);
  System.out.println("The price is "+ ref4.price);
  System.out.println("-------------------------------------------------------------------");
   NewsPaper1 ref5 = new NewsPaper1();
	 ref5.currentAffairs();
	 ref5.companyName = "Dainik Jagran";
	 ref5.noOfPages = "11";
	 ref5.language = "Hindi";
	 ref5.price = 30;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref5.companyName);
  System.out.println("The noOfPages is "+ ref5.noOfPages);
  System.out.println("The language is "+ ref5.language);
  System.out.println("The price is "+ ref5.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref6 = new NewsPaper1();
	 ref6.currentAffairs();
	 ref6.companyName = "Independent Morning";
	 ref6.noOfPages = "11";
	 ref6.language = "Hindi";
	 ref6.price = 30;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref6.companyName);
  System.out.println("The noOfPages is "+ ref6.noOfPages);
  System.out.println("The language is "+ ref6.language);
  System.out.println("The price is "+ ref6.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref7 = new NewsPaper1();
	 ref7.currentAffairs();
	 ref7.companyName = "Sunrise Record";
	 ref7.noOfPages = "17";
	 ref7.language = "English";
	 ref7.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref7.companyName);
  System.out.println("The noOfPages is "+ ref7.noOfPages);
  System.out.println("The language is "+ ref7.language);
  System.out.println("The price is "+ ref7.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref8 = new NewsPaper1();
	 ref8.currentAffairs();
	 ref8.companyName = "The News Glory";
	 ref8.noOfPages = "17";
	 ref8.language = "English";
	 ref8.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref8.companyName);
  System.out.println("The noOfPages is "+ ref8.noOfPages);
  System.out.println("The language is "+ ref8.language);
  System.out.println("The price is "+ ref8.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref9 = new NewsPaper1();
	 ref9.currentAffairs();
	 ref9.companyName = "Journal Daily";
	 ref9.noOfPages = "17";
	 ref9.language = "Hindi";
	 ref9.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref9.companyName);
  System.out.println("The noOfPages is "+ ref9.noOfPages);
  System.out.println("The language is "+ ref9.language);
  System.out.println("The price is "+ ref9.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref10 = new NewsPaper1();
	 ref10.currentAffairs();
	 ref10.companyName = "Rocky Mountain News";
	 ref10.noOfPages = "18";
	 ref10.language = "English";
	 ref10.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref10.companyName);
  System.out.println("The noOfPages is "+ ref10.noOfPages);
  System.out.println("The language is "+ ref10.language);
  System.out.println("The price is "+ ref10.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref11 = new NewsPaper1();
	 ref11.currentAffairs();
	 ref11.companyName = "The daily emporium";
	 ref11.noOfPages = "19";
	 ref11.language = "hindi";
	 ref11.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref11.companyName);
  System.out.println("The noOfPages is "+ ref11.noOfPages);
  System.out.println("The language is "+ ref11.language);
  System.out.println("The price is "+ ref11.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref12 = new NewsPaper1();
	 ref12.currentAffairs();
	 ref12.companyName = "Enquirer";
	 ref12.noOfPages = "19";
	 ref12.language = "hindi";
	 ref12.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref12.companyName);
  System.out.println("The noOfPages is "+ ref12.noOfPages);
  System.out.println("The language is "+ ref12.language);
  System.out.println("The price is "+ ref12.price);
  System.out.println("-------------------------------------------------------------------");
   NewsPaper1 ref13 = new NewsPaper1();
	 ref13.currentAffairs();
	 ref13.companyName = "Evening Enterprise";
	 ref13.noOfPages = "19";
	 ref13.language = "hindi";
	 ref13.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref12.companyName);
  System.out.println("The noOfPages is "+ ref12.noOfPages);
  System.out.println("The language is "+ ref12.language);
  System.out.println("The price is "+ ref12.price);
  System.out.println("-------------------------------------------------------------------");
  NewsPaper1 ref14 = new NewsPaper1();
	 ref14.currentAffairs();
	 ref14.companyName = "Entrepreneur";
	 ref14.noOfPages = "19";
	 ref14.language = "English";
	 ref14.price = 20;
	 System.out.println("----------------------------------------------------------------");
  System.out.println("The Company name is "+ ref14.companyName);
  System.out.println("The noOfPages is "+ ref14.noOfPages);
  System.out.println("The language is "+ ref14.language);
  System.out.println("The price is "+ ref14.price);
  System.out.println("-------------------------------------------------------------------");
  }
}
