class ShampooRunner
{
	public static void main(String [] Shampooo)
	{
		Shampoo ref = new Shampoo();
		ref.purpose();
		ref.brandName = "Dove";
		ref.id = 1;
		ref.quantity = 100;
		ref.type = "smoothening";
		ref.price = 2.00;
		ref.mgfDate = "17/07/2024";
		ref.expDate = "24/05/2025";
		System.out.println("The brand name is: " + ref.brandName);
		System.out.println("The id is: " + ref.id);
		System.out.println("The quantity we want is: " + ref.quantity);
		System.out.println("The special for : " + ref.type);
		System.out.println("The peice is: " + ref.price);
		System.out.println("The manufacture date is: " + ref.mgfDate);
		System.out.println("The expire date is: " + ref.expDate);
		System.out.println("-------------------------------------------------------------------------");
		
		Shampoo ref1 = new Shampoo();
		ref1.purpose();
		ref1.brandName = "Garnier";
		ref1.id = 2;
		ref1.quantity = 50;
		ref1.type = "Anti-dandruff";
		ref1.price = 5.00;
		ref1.mgfDate = "7/06/2024";
		ref1.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref1.brandName);
		System.out.println("The id is: " + ref1.id);
		System.out.println("The quantity we want is: " + ref1.quantity);
		System.out.println("The special for : " + ref1.type);
		System.out.println("The peice is: " + ref1.price);
		System.out.println("The manufacture date is: " + ref1.mgfDate);
		System.out.println("The expire date is: " + ref1.expDate);
		System.out.println("-------------------------------------------------------------------------");

		Shampoo ref2 = new Shampoo();
		ref2.purpose();
		ref2.brandName = "Pantene";
		ref2.id = 3;
		ref2.quantity = 10;
		ref2.type = "Smoothening";
		ref2.price = 10.00;
		ref2.mgfDate = "7/06/2024";
		ref2.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref2.brandName);
		System.out.println("The id is: " + ref2.id);
		System.out.println("The quantity we want is: " + ref2.quantity);
		System.out.println("The special for : " + ref2.type);
		System.out.println("The peice is: " + ref2.price);
		System.out.println("The manufacture date is: " + ref2.mgfDate);
		System.out.println("The expire date is: " + ref2.expDate);
		System.out.println("-------------------------------------------------------------------------");
		
		Shampoo ref3 = new Shampoo();
		ref3.purpose();
		ref3.brandName = "Head & Shoulder";
		ref3.id = 4;
		ref3.quantity = 10;
		ref3.type = "Dandruff removal";
		ref3.price = 2.00;
		ref3.mgfDate = "7/06/2024";
		ref3.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref3.brandName);
		System.out.println("The id is: " + ref3.id);
		System.out.println("The quantity we want is: " + ref3.quantity);
		System.out.println("The special for : " + ref3.type);
		System.out.println("The peice is: " + ref3.price);
		System.out.println("The manufacture date is: " + ref3.mgfDate);
		System.out.println("The expire date is: " + ref3.expDate);
		System.out.println("-------------------------------------------------------------------------");
		
		Shampoo ref4 = new Shampoo();
		ref4.purpose();
		ref4.brandName = "Loreal";
		ref4.id = 5;
		ref4.quantity = 20;
		ref4.type = "Smoothening";
		ref4.price = 10.00;
		ref4.mgfDate = "20/06/2024";
		ref4.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref4.brandName);
		System.out.println("The id is: " + ref4.id);
		System.out.println("The quantity we want is: " + ref4.quantity);
		System.out.println("The special for : " + ref4.type);
		System.out.println("The peice is: " + ref4.price);
		System.out.println("The manufacture date is: " + ref4.mgfDate);
		System.out.println("The expire date is: " + ref4.expDate);
		System.out.println("-------------------------------------------------------------------------");
		
		Shampoo ref5 = new Shampoo();
		ref5.purpose();
		ref5.brandName = "Schwarzkopf";
		ref5.id = 6;
		ref5.quantity = 100;
		ref5.type = "Hair care";
		ref5.price = 10.00;
		ref5.mgfDate = "9/05/2024";
		ref5.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref5.brandName);
		System.out.println("The id is: " + ref5.id);
		System.out.println("The quantity we want is: " + ref5.quantity);
		System.out.println("The special for : " + ref5.type);
		System.out.println("The peice is: " + ref5.price);
		System.out.println("The manufacture date is: " + ref5.mgfDate);
		System.out.println("The expire date is: " + ref5.expDate);
		System.out.println("-------------------------------------------------------------------------");

		Shampoo ref6 = new Shampoo();
		ref6.purpose();
		ref6.brandName = "Sunsilk";
		ref6.id = 7;
		ref6.quantity = 10;
		ref6.type = "Reduces hair breakage";
		ref6.price = 10.00;
		ref6.mgfDate = "7/06/2024";
		ref6.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref6.brandName);
		System.out.println("The id is: " + ref6.id);
		System.out.println("The quantity we want is: " + ref6.quantity);
		System.out.println("The special for : " + ref6.type);
		System.out.println("The peice is: " + ref6.price);
		System.out.println("The manufacture date is: " + ref6.mgfDate);
		System.out.println("The expire date is: " + ref6.expDate);
		System.out.println("-------------------------------------------------------------------------");
	
		Shampoo ref7 = new Shampoo();
		ref7.purpose();
		ref7.brandName = "TRESemme";
		ref7.id = 8;
		ref7.quantity = 30;
		ref7.type = "Shining";
		ref7.price = 5.00;
		ref7.mgfDate = "7/06/2024";
		ref7.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref7.brandName);
		System.out.println("The id is: " + ref7.id);
		System.out.println("The quantity we want is: " + ref7.quantity);
		System.out.println("The special for : " + ref7.type);
		System.out.println("The peice is: " + ref7.price);
		System.out.println("The manufacture date is: " + ref7.mgfDate);
		System.out.println("The expire date is: " + ref7.expDate);
		System.out.println("-------------------------------------------------------------------------");
		
		Shampoo ref8 = new Shampoo();
		ref8.purpose();
		ref8.brandName = "Aussie";
		ref8.id = 9;
		ref8.quantity = 10;
		ref8.type = "Prepare hair damage";
		ref8.price = 10.00;
		ref8.mgfDate = "7/06/2024";
		ref8.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref8.brandName);
		System.out.println("The id is: " + ref8.id);
		System.out.println("The quantity we want is: " + ref8.quantity);
		System.out.println("The special for : " + ref8.type);
		System.out.println("The peice is: " + ref8.price);
		System.out.println("The manufacture date is: " + ref8.mgfDate);
		System.out.println("The expire date is: " + ref8.expDate);
		System.out.println("-------------------------------------------------------------------------");

		Shampoo ref9 = new Shampoo();
		ref9.purpose();
		ref9.brandName = "Pantene";
		ref9.id = 10;
		ref9.quantity = 50;
		ref9.type = "Smoothening";
		ref9.price = 10.00;
		ref9.mgfDate = "7/06/2024";
		ref9.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref9.brandName);
		System.out.println("The id is: " + ref9.id);
		System.out.println("The quantity we want is: " + ref9.quantity);
		System.out.println("The special for : " + ref9.type);
		System.out.println("The peice is: " + ref9.price);
		System.out.println("The manufacture date is: " + ref9.mgfDate);
		System.out.println("The expire date is: " + ref9.expDate);
		System.out.println("-------------------------------------------------------------------------");
		
		Shampoo ref10 = new Shampoo();
		ref10.purpose();
		ref10.brandName = "Herbal Essences";
		ref10.id = 10;
		ref10.quantity = 50;
		ref10.type = "Ayurvedic";
		ref10.price = 10.00;
		ref10.mgfDate = "7/06/2024";
		ref10.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref10.brandName);
		System.out.println("The id is: " + ref10.id);
		System.out.println("The quantity we want is: " + ref10.quantity);
		System.out.println("The special for : " + ref10.type);
		System.out.println("The peice is: " + ref10.price);
		System.out.println("The manufacture date is: " + ref10.mgfDate);
		System.out.println("The expire date is: " + ref10.expDate);
		System.out.println("-------------------------------------------------------------------------");

		Shampoo ref11 = new Shampoo();
		ref11.purpose();
		ref11.brandName = "Chillout haircare";
		ref11.id = 12;
		ref11.quantity = 50;
		ref11.type = "haircare";
		ref11.price = 10.00;
		ref11.mgfDate = "7/06/2024";
		ref11.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref11.brandName);
		System.out.println("The id is: " + ref11.id);
		System.out.println("The quantity we want is: " + ref11.quantity);
		System.out.println("The special for : " + ref11.type);
		System.out.println("The peice is: " + ref11.price);
		System.out.println("The manufacture date is: " + ref11.mgfDate);
		System.out.println("The expire date is: " + ref11.expDate);
		System.out.println("-------------------------------------------------------------------------");
		
		Shampoo ref12 = new Shampoo();
		ref12.purpose();
		ref12.brandName = "Chick";
		ref12.id = 13;
		ref12.quantity = 1;
		ref12.type = "Cleaning";
		ref12.price = 10.00;
		ref12.mgfDate = "7/06/2024";
		ref12.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref12.brandName);
		System.out.println("The id is: " + ref12.id);
		System.out.println("The quantity we want is: " + ref12.quantity);
		System.out.println("The special for : " + ref12.type);
		System.out.println("The peice is: " + ref12.price);
		System.out.println("The manufacture date is: " + ref12.mgfDate);
		System.out.println("The expire date is: " + ref12.expDate);
		System.out.println("-------------------------------------------------------------------------");
		
		Shampoo ref13 = new Shampoo();
		ref13.purpose();
		ref13.brandName = "Pantene";
		ref13.id = 10;
		ref13.quantity = 50;
		ref13.type = "Smoothening";
		ref13.price = 10.00;
		ref13.mgfDate = "7/06/2024";
		ref13.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref13.brandName);
		System.out.println("The id is: " + ref13.id);
		System.out.println("The quantity we want is: " + ref13.quantity);
		System.out.println("The special for : " + ref13.type);
		System.out.println("The peice is: " + ref13.price);
		System.out.println("The manufacture date is: " + ref13.mgfDate);
		System.out.println("The expire date is: " + ref13.expDate);
		System.out.println("-------------------------------------------------------------------------");

		Shampoo ref14 = new Shampoo();
		ref14.purpose();
		ref14.brandName = "Clinic plus";
		ref14.id = 15;
		ref14.quantity = 50;
		ref14.type = "Smoothening";
		ref14.price = 10.00;
		ref14.mgfDate = "7/06/2024";
		ref14.expDate = "4/05/2025";
		System.out.println("The brand name is: " + ref14.brandName);
		System.out.println("The id is: " + ref14.id);
		System.out.println("The quantity we want is: " + ref14.quantity);
		System.out.println("The special for : " + ref14.type);
		System.out.println("The peice is: " + ref14.price);
		System.out.println("The manufacture date is: " + ref14.mgfDate);
		System.out.println("The expire date is: " + ref14.expDate);
		System.out.println("-------------------------------------------------------------------------");
		}
}